### PR TITLE
Additional results

### PR DESCRIPTION
**Pull request by Clare2D**
- Added new charts
- Updated the results to be more relevant
- convert to tonnes
- changed C to c (formatting preference)
- Updated the sample parameter file to reflect new content
- Added hectares as an input parameter
- Added an initial and future carbon input 

This was all done during the Team Retreat, just pushing now

### CODE REVIEW

**Comment by bimtauer** [comment]
Just for my understanding: Apart from new helper and plotting functions, you now distinguish between c_inputs_base - the baseline and c_inputs_reg, the RegenAg scenario and run the model for both, however not to compare the two on the same timeframe, but to model what initial values the baseline scenario would converge to over 500 years. Is that right?

**Comment by Clare2D** [comment]
That's exactly right. It seems to be the standard way of using the model. The steps when we get real data will be rather to use the real values rather than back modelling 500 years - however I'm not entirely sure what should be a variable - because if we get a real value it will not represent the breakdown of the soil into the five components, rather the total carbon in the soil. It could be used to calibrate the average carbon in, or at least to compare this value to what we use.. but I'm not sure about that either. I guess we can cross this bridge a little later though

**Comment by bimtauer** [comment]
Ok great! Afaik, If you know the soc content, you can approximate IOM using either IOM = 10^(−1.31+1.139⋅log10(soc_ini)) (Falloon et al., 1998) or IOM = 0.049⋅SOC^1.139 ([Uni Jena](https://www.bgc-jena.mpg.de/TEE/basics/2015/11/19/RothC/))
Having that you can apparently assume the following distribution over the other stocks: 
[DPM, RPM, BIO, HUM] = (soc_ini - IOM) * [0.0065, 0.1500,  0.0212,  0.8224]

Did you also encounter these approximations?

**Comment by Clare2D** [comment]
Ah of course, forgot about that. I read at one point that it is not ideal to calibrate the model from one single data point, so I guess we should compare possibly the modelled version and the data point and if they are wildly different.... do something about it?

**Comment by Clare2D** [comment]
I guess we will also need to use the measurement and vary for the time of year so we could extrapolate (or calculate) so that we've got the expected levels for January rather than any time of year - or start RothC at a different month (which is more difficult I believe)

**Pull request merged**
